# Generated by Django 5.0.3 on 2024-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='grap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
