# Generated by Django 5.0.3 on 2024-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_types_grap'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
