# Generated by Django 5.0.3 on 2024-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_product_grap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='types',
            name='grap',
            field=models.CharField(max_length=100),
        ),
    ]
