# Generated by Django 5.0.3 on 2024-03-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_number_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.IntegerField(),
        ),
    ]
