# Generated by Django 5.0.3 on 2024-03-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_email_employee_hire_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
