# Generated by Django 5.0.3 on 2024-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
