# Generated by Django 5.0.3 on 2024-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('earning', models.IntegerField()),
                ('purchases', models.IntegerField()),
            ],
        ),
    ]
