# Generated by Django 5.0.3 on 2024-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='earning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chart',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chart',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
