# Generated by Django 5.0.3 on 2024-04-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chart_earning_alter_chart_purchases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(default=0)),
                ('customers', models.IntegerField(default=0)),
                ('earning', models.IntegerField(default=0)),
                ('day', models.IntegerField()),
            ],
        ),
    ]
