# Generated by Django 5.0.3 on 2024-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='prouducts',
            field=models.IntegerField(default=0),
        ),
    ]
